services:
  task-manager:
    extends:
      file: ./task_manager/docker-compose.yaml
      service: task-manager
    build:
      context: .
    environment:
      - HTTP_PROXY=hoverfly:8500
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - LOCATION_SERVICE=location-service:8001
    volumes:
      - ./task_manager:/app/task_manager
    depends_on:
      - hoverfly
