services:
  task-manager:
    build:
      context: .
      dockerfile: ./task_manager/Dockerfile
    image: task-manager:0.1
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - LOCATION_SERVICE=location-service:8001
    ports:
      - 8000:8000
    expose:
      - 8000
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/ping" ]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 5s
    volumes:
      - ./task_manager:/app/task_manager
    depends_on:
      - redis
    networks:
      - redis-network
      - location-network
      - monitoring-network