services:
  event-service:
    extends:
      file: ./event_service/docker-compose.yaml
      service: event-service
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PUSH_GATEWAY_HOST=push-gateway
      - PUSH_GATEWAY_PORT=9091
      - HTTP_PROXY=hoverfly:8500
    depends_on:
      - hoverfly
