services:
  event-service:
    build:
      context: event_service
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PUSH_GATEWAY_HOST=push-gateway
      - PUSH_GATEWAY_PORT=9091
    depends_on:
      - redis
    networks:
      - redis-network
      - monitoring-network