services:
  redis:
    image: redis
    ports:
      - 6379:6379
    labels:
      - compose.task_manager=task-manager
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - redis-data:/data
    entrypoint: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      - redis-network
volumes:
  redis-data:
    labels:
      - compose-app=task-manager
networks:
  redis-network:
  location-network:
  monitoring-network: