services:
  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - 8000:8000
    networks:
      - aws-internal
    expose:
      - 8000
  dynamodb-initializer:
    image: amazon/aws-cli
    env_file:
      - ./mock_credentials.env
    entrypoint: '/create_table.sh'
    depends_on:
      - dynamodb
    volumes:
      - ./create_table.sh:/create_table.sh
    networks:
      - aws-internal
  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    env_file:
      - ./mock_credentials.env
    environment:
      - DYNAMO_ENDPOINT=http://dynamodb:8000
      - AWS_REGION=eu-west-2
      - AWS_ACCESS_KEY_ID=fakeMyKeyId
      - AWS_SECRET_ACCESS_KEY=fakeSecretAccessKey
    ports:
      - 8001:8001
    expose:
      - 8001
    networks:
      - aws-internal
  sqs:
    image: softwaremill/elasticmq
    ports:
      - 9324:9324
      - 9325:9325
    networks:
      - aws-internal
    volumes:
      - ./sqs.conf:/opt/elasticmq.conf
  s3:
    image: adobe/s3mock
    ports:
      - 9090:9090
    networks:
      - aws-internal
    environment:
      - initialBuckets=subscription-bucket
networks:
  aws-internal:
  aws-public: