services:
  nginx:
    image: custom-nginx:0.1
    ports:
      - 8080:80
    volumes:
      - ./static-site:/usr/share/nginx/html
  redis:
    image: redis
    ports:
      - 6379:6379
  api:
    build:
      context: .
      dockerfile: .docker/app/Dockerfile
    ports:
      - 8000:8000
    expose:
      - 8000
    volumes:
      - ./api:/app/api
