# You can create merged config from several docker-files with "docker compose config" command
name: compose
services:
  location-service:
    build:
      context: /home/k_eryomenko/github/compose
      dockerfile: ./location_service/Dockerfile
    depends_on:
      redis:
        condition: service_started
        required: true
    environment:
      REDIS_HOST: redis
      REDIS_PORT: "6379"
    expose:
      - "8001"
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:8001/ping
      timeout: 10s
      interval: 20s
      retries: 5
      start_period: 5s
    image: location-service:0.1
    networks:
      location-network: null
      monitoring-network: null
      redis-network: null
    ports:
      - mode: ingress
        target: 8001
        published: "8001"
        protocol: tcp
    volumes:
      - type: bind
        source: /home/k_eryomenko/github/compose/location_service
        target: /app/location_service
        bind:
          create_host_path: true
  redis:
    entrypoint:
      - redis-server
      - /usr/local/etc/redis/redis.conf
    image: redis
    labels:
      compose.task_manager: task-manager
    networks:
      redis-network: null
    ports:
      - mode: ingress
        target: 6379
        published: "6379"
        protocol: tcp
    volumes:
      - type: bind
        source: /home/k_eryomenko/github/compose/redis/redis.conf
        target: /usr/local/etc/redis/redis.conf
        bind:
          create_host_path: true
      - type: volume
        source: redis-data
        target: /data
        volume: {}
networks:
  location-network:
    name: compose_location-network
  monitoring-network:
    name: compose_monitoring-network
  redis-network:
    name: compose_redis-network
volumes:
  redis-data:
    name: compose_redis-data
    labels:
      compose-app: task-manager
