services:
  sqs-to-lambda:
    build:
      context: .
      dockerfile: ./sqs-to-lambda/Dockerfile
    image: sqs-to-lambda
    environment:
     - SQS_TOPIC=/000000000000/subscription-event
     - S3STORE_LAMBDA_ENDPOINT=http://s3store-lambda:8080/2015-03-31/functions/function/invocations
     - SQS_ENDPOINT=http://sqs:9324
    depends_on:
      - s3store-lambda
    env_file:
      - ./mock_credentials.env
    networks:
      aws-internal: