services:
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./monitoring/prometheus.yaml:/etc/prometheus/prometheus.yml
      - ./monitoring/alerts.yaml:/etc/prometheus/alerts.yaml
    networks:
      - monitoring-network
  push-gateway:
    image: prom/pushgateway
    networks:
      - monitoring-network
    ports:
      - 9091:9091
    expose:
      - 9091